---
book_repo: pivotal-cf/docs-book-tiledev
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'edge'
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: pivotal-cf/docs-tiledev
    ref: 'master'
  directory: tiledev/2-n
  subnav_template: tiledev_subnav_2_n.erb
  product_info:
    use_local_header: true
    latest_stable_version: '2.8'
    changelog_href: http://docs.pivotal.io/tiledev/2-n/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Platform Tile Developer Guide
    search_placeholder: Search Pivotal Platform Tile Developer Guide 2.n
    local_product_version: '2.9'
    url_prefix: tiledev/2-n
    local_header_links:
      - <a href="https://network.pivotal.io/">Download</a>
      - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
      - <a href="https://community.pivotal.io/s/topic/0TO0P000000IKhwWAG/welcome">Pivotal Support Community</a>
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/tiledev/2-8
        display_name: v2.8
      - url_prefix: https://docs.pivotal.io/tiledev/2-7
        display_name: v2.7
      - url_prefix: https://docs.pivotal.io/tiledev/2-6
        display_name: v2.6
      - url_prefix: https://docs.pivotal.io/tiledev/2-5
        display_name: v2.5
      - url_prefix: https://docs.pivotal.io/tiledev/2-4
        display_name: v2.4
      - url_prefix: https://docs.pivotal.io/tiledev/2-3
        display_name: v2.3
      - url_prefix: https://docs.pivotal.io/tiledev/2-2
        display_name: v2.2
      - <a href="https://resources.docs.pivotal.io/pdfs/tiledev-guide-2.1.pdf">v2.1</a>
      - <a href="https://resources.docs.pivotal.io/pdfs/tiledev-guide-2.0.pdf">v2.0</a>
      - <a href="https://resources.docs.pivotal.io/pdfs/tiledev-guide-1.12.pdf">v1.12</a>
- repository:
    name: cloudfoundry/docs-services
    ref: 'master'
  directory: brokers/2-n
  subnav_template: tiledev_subnav_2_n.erb
  product_info:
    use_local_header: true
    latest_stable_version: '2.7'
    changelog_href: http://docs.pivotal.io/tiledev/2-n/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Platform Tile Developer Guide
    search_placeholder: Search Platform Developer Guide 2.n
    local_product_version: '2.8'
    url_prefix: brokers/2-n
    local_header_links:
      - <a href="https://network.pivotal.io/">Download</a>
      - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
      - <a href="https://discuss.pivotal.io/hc/en-us/categories/200072648-Pivotal-CF-Knowledge-Base">Pivotal Platform Knowledge Base</a>
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/brokers/2-7
        display_name: v2.7
      - url_prefix: https://docs.pivotal.io/brokers/2-6
        display_name: v2.6
      - url_prefix: https://docs.pivotal.io/brokers/2-5
        display_name: v2.5
      - url_prefix: https://docs.pivotal.io/brokers/2-4
        display_name: v2.4
      - url_prefix: https://docs.pivotal.io/brokers/2-3
        display_name: v2.3
      - url_prefix: https://docs.pivotal.io/brokers/2-2
        display_name: v2.2
      - <a href="https://resources.docs.pivotal.io/pdfs/tiledev-guide-2.1.pdf">v2.1</a>
      - <a href="https://resources.docs.pivotal.io/pdfs/tiledev-guide-2.0.pdf">v2.0</a>
      - <a href="https://resources.docs.pivotal.io/pdfs/tiledev-guide-1.12.pdf">v1.12</a>

# cross-product resources

- repository:
    name: pivotal-cf/docs-partials
    ref: 'master'
  directory: pcf
  no_docs: true
